### ISSUE TITLE
Release new version without print statements

### ISSUE THREAD

**Issue by andys8** [eir-forsakring/aws-lambda-haskell-runtime-wai#3]
I've noticed there were `print` statements. They were removed from the source, but as of today, no new version was released. Is it possible to release a new version without the print statements?

https://github.com/eir-forsakring/aws-lambda-haskell-runtime-wai/commit/2f7b4007a0149ef6562517faca94201fff8d6e0a#diff-7e4d7ac297643df5f57ed72e9fc6e20c

> "Working: Something went wai"

**Comment by dnikolovv** [comment]
Sorry about that! I honestly forgot this was up on Hackage, since we're still using a git dependency.

I'll release a new version in a few minutes.

**Comment by dnikolovv** [comment]
Alright. Version `1.0.1` is up on Hackage. That also includes your query string hotfix. Thanks again!

**Comment by andys8** [comment]
@dnikolovv https://github.com/theam/aws-lambda-haskell-runtime/pull/87 was merged :)
