### ISSUE TITLE
Race condition after first request.

### ISSUE THREAD

**Issue by freuk** [eir-forsakring/aws-lambda-haskell-runtime-wai#7]
Hi and thanks for sharing this compatibility layer.

The GHC runtime detects a race condition on every request on my lambda function except the first one, which works fine: `the second thread blocked indefinitely in an MVar operation`.

I'm using the `waiHandler` handler. Have you encountered such issues?

**Comment by dnikolovv** [comment]
Hi! We haven't encountered that and we've been using this library in production for a few months now.

Can you check whether you get the same behaviour with https://github.com/eir-forsakring/aws-lambda-haskell-runtime-wai/tree/runtime-v4? This is the one we currently use.

If you can also provide a repro, that'd be great!

Also, how are you building the executable?

**Comment by freuk** [comment]
Thanks for your lightning fast reply. I think it's up to the code in `processRequest`. I will try the v4 and try to minimize my code down to a repro, yes.

I'm shipping a container image using the second method described in https://github.com/freuk/serverless-haskell-nix

**Comment by freuk** [comment]
A more on-point answer to your second question is that I'm using cabal and passing `-threaded -rtsopts -with-rtsopts=-N` to GHC, similarly to the WAI example you show in the `aws-lambda-haskell-runtime`repository.

**Comment by dnikolovv** [comment]
Hmm, nothing unusual it seems. I guess we just need to get to a repro.

**Comment by freuk** [comment]
~Is the compatible `aws-lambda-haskell-runtime` fork for the branch you pointed to the one located at https://github.com/dnikolovv/aws-lambda-haskell-runtime/tree/no-th-4.0.0 ?~
Nevermind, I found the location of the necessary commit. Sorry for the noise.

**Comment by freuk** [comment]
Switching to your runtime-v4 solved the issue. I'll stop investigating, sorry for the lack of closure and thank you for the pointer!

**Comment by dnikolovv** [comment]
No worries, thank you for reporting!
